---
apiVersion: v1
kind: ReplicationController
metadata:
  name: eureka-master
spec:
  replicas: 1
  selector:
    app: eureka-master
  template:
    metadata:
      labels:
        app: eureka-master
    spec:
      containers:
      - name: eureka-master
        image: kadanli/eureka:v0.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8761
---
apiVersion: v1
kind: Service
metadata:
  name: eureka-master
spec:
  type: NodePort
  ports:
    - port: 8761
      nodePort: 30006
  selector:
    app: eureka-master
